### ISSUE TITLE
Add Browser extension POC

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-server#1]
@jdkato I'd love if you could push the code you had working as a browser extension as a POC branch. I was going to push mine and then looked through it, but I must have reverted some changes in frustration and it wasn't under version control, so can't find it now :(

Then I might take another look at that.

**Comment by jdkato** [comment]
My major development goal for 2019 is to make Vale more "mainstream" (if you will) and, in order to do that, I've been working on a number of new features:

- I plan to release Vale Server as a commercial desktop app that communicates with the (soon-to-be-released) Google Docs, Microsoft Word, and browser extensions. I've put a lot of work into making this easy-to-use (especially for people without command-line experience, which is probably the majority of the mainstream market) and lightweight (it's native C++, not another Electron app). 

- I'm working on 3 new styles (which will be open source): the Microsoft Writing Style Guide, Google Developer Documentation Style Guide, and one I'm calling "Grammar" (which should be comparable to LanguageTool's English functionality).

- A new website that better explains Vale, its goals, and how it's different from other options.

So, while I'm typically 100% pro OSS, I'm hoping that Vale Server can help me dedicate more time (financially speaking) to developing the project as a whole.

**Comment by ChrisChinchilla** [comment]
@jdkato Sorry got very behind with things, catching up a little now. My main point was that there are a few of us who want to help and want to collaborate. Some of us have already started creating equivalent PoCs of some of the ideas we discussed recently. So it would be nice to work on ideas together instead of duplicating efforts, which means putting our code somewhere.

Maybe we can create a private repo for these projects? I'm happy to cover costs if need be, I'm mostly keen and enthusiastic to get these efforts happening and unified.

We all appreciate the effort you have put in so far, and want you to be rewarded for that, but we also want to help :)

**Comment by jdkato** [comment]
Oh, I don't intend to change the status of the currently open-source aspects of Vale (and I appreciate the help I've received from a number of contributors, yourself included).

I merely meant to explain that I'm planning to release some closed-source projects this year, which is why I haven't posted the source for the browser extension.

**Comment by ChrisChinchilla** [comment]
@jdkato sure, I think I meant that some of us here are happy to help with those closed source projects too ;)

Or you might end up with open source alternatives from some of those same people anyway.
