### ISSUE TITLE
Questions about having single source of truth for Vale rules

### ISSUE THREAD

**Issue by Sterling463** [errata-ai/vale-server#12]
I am attempting to set up the Vale server for our organization. The intended workflow will be to use a few 3rd party styles - MS and Google- and then create organization specific styles that exist simultaneously on everyone's computer (maybe though Git?)

I have attempted a few things: 

1. Creating a symlink from the vale server directory to the git location of the custom files
2. Placing the .ini and custom styles in the same directory as the content we would like to lint (This is not ideal since we are using multiple repos) but none of these seem to be working. 

Is there a way to accomplish what I am trying to do?

**Comment by jdkato** [comment]
There are a few options:

- If you're satisfied with how the third-party styles are managed through the Dashboard UI, you can add your organization-specific style to the [open-source library](https://github.com/errata-ai/styles) and it'll be handled the same way.

- If you want to use Git to manage organization-specific style, you can clone the style repository directly into Vale Server's `StylesPath` (you can find this directory via [Preferences -> Browse Styles](https://errata-ai.github.io/vale-server/docs/ui#preferences)). This is basically your option (1) above except, instead of cloning the repo somewhere else and then symlinking back, you're just directly cloning into the `StylesPath` (i.e., no need for a symlink).

- Option (2) above *should* work (I personally use it for many projects) and we can investigate why it isn't if you're interested in pursuing it it (but it seems like one of the previous options might be better). 

Let me know if I need explain or clarify any of these options in more depth.

**Comment by Sterling463** [comment]
Thanks. This clears it up.

**Comment by Sterling463** [comment]
Option 2 worked well for a few days but it seems like Vale automatically cleans up the StylesPath anytime a Style is updated. This deletes the cloned repo and requires that we add it again. Is this something you have noticed/ have a fix for?

**Comment by jdkato** [comment]
I haven't noticed this, but I'd certainly like to fix it.

To make sure we're on the same page:

1. You cloned an organization-specific style (with a name that doesn't collide with any of the managed styles -- e.g., something like `MyCompany`) into your `StylesPath`.
2. You then used the Dashboard to update another style (e.g., `Microsoft`).
3. Your `MyCompany` was then deleted?

**Comment by Sterling463** [comment]
That is correct. I was able to clone it again but I don't know if Vale is deleting the entire repository and then repopulating with new styles whenever there is an update?

**Comment by jdkato** [comment]
I've spent some time looking into this (Vale Server v1.3.0) and I've been unable to reproduce the behavior. For example, given the following `StylesPath` (`Library/Application Support/errata-ai/Vale Server/styles` for me):

```text
.
├── Cloned <-- My "cloned" style
├── Google
├── Joblint
├── Microsoft
├── Vocab
├── proselint
└── write-good
```

The only folder that is removed is the specific one being updated&mdash;so, if I were updating `Joblint`, any content stored in `StylesPath/Joblint` is removed but `Cloned` (a sibling directory) is left intact.

Is it possible that your custom style was cloned into a subirectory of `StylesPath`?

**Comment by Sterling463** [comment]
I haven't had this happen again. It is possible that the problem was on my end. Closing this for now. Thanks for the help.
