### ISSUE TITLE
Unable to load / list available styles in the Styles tab

### ISSUE THREAD

**Issue by yohannes** [errata-ai/vale-server#65]
Hi all.

Unable to load / list available styles in the Styles tab / window. Tried on the latest Chrome, Safari, & Firefox browsers but the loading indicator kept spinning (see [screenshot](https://imgur.com/a/CirLitc)). Any pointer on what may cause the issue?

Best,
Yohannes

**Comment by jdkato** [comment]
Hi -- it looks like you need to [create a project](https://docs.errata.ai/vale-server/gui#projects). Where the sidebar currently says `Project: N/A`, it should display the name of your active project (this determines where the styles are installed, among other things).

I'll add a message to the Dashboard in the next release instead of the spinning icon in this case.

**Comment by jdkato** [comment]
Were you able to resolve this?

**Comment by yohannes** [comment]
Hi @jdkato, I've managed to install the styles successfully as you suggested. Thanks. However, when clicking the vale plugin icon on the chrome's menu bar while editing a google doc, I got a popup that said _"no content found; try editing some text and then clicking the icon"_ - to which I did. Suggestion?

**Comment by jdkato** [comment]
There are some restrictions about what content the Chrome extension can and cannot access. In general, it can access standalone text fields (such as email, social media, GitHub, etc.) but not app-specific editors like Google Docs. 

There is [Google Docs add-on](https://docs.errata.ai/vale-server/clients/google-docs), though.

**Comment by yohannes** [comment]
@jdkato noted. Thanks for your reply.
